name: Create a comment on a new issue

on:
    issues: 
        types: [opened]

jobs:
    comment-with-action:
        runs-on: ubuntu-latest
        steps:
            - name: "Step: Dump GitHub Context"
              run: echo '${{ toJSON(github.event) }}' | jq
              shell: bash
            - name: Create comment
              uses: peter-evans/create-or-update-comment@v4
              with:
                issue-number: ${{ github.event.issue.number }}
                body: |
                    This is a multi-line test comment
                    - With GitHub **Markdown** :sparkles:
                    - Created by [create-or-update-comment][1]
        
                    [1]: https://github.com/peter-evans/create-or-update-comment
                reactions: '+1'
            - name: Update comment
              uses: peter-evans/create-or-update-comment@v4
              with:
                comment-id: ${{ github.event.issue.id }}
                body: |
                 **Edit:** Some additional info
                reactions: eyes

            - name: Add reactions
              uses: peter-evans/create-or-update-comment@v4
              with:
                comment-id: ${{ github.event.issue.id }}
                reactions: |
                    heart
                    hooray
                    laugh